# Mise configuration for development tools
# This file defines the tools and their versions to be installed

[tools]
# Programming languages
python = "3.12"
node = "20"
go = "1.21"

# CLI tools
"cargo:eza" = "latest"      # Modern replacement for ls
"cargo:bat" = "latest"      # Modern replacement for cat
"cargo:ripgrep" = "latest"  # Modern replacement for grep
"cargo:fd" = "latest"       # Modern replacement for find
"cargo:delta" = "latest"    # Better git diffs

[settings]
experimental = true
