[tools]
"aqua:exercism/cli" = "latest"
"aqua:github/copilot-cli" = "latest"
"aqua:iawia002/lux" = "latest"
"aqua:nats-io/natscli" = "latest"
"aqua:peteretelej/tree" = "latest"
"aqua:topgrade-rs/topgrade" = "latest"
"aqua:uutils/coreutils" = "latest"
"aqua:zyedidia/micro" = "latest"
"aqua:Wilfred/difftastic" = "latest"
bat = "latest"
bottom = "latest"
bun = "latest"
carapace = "latest"
cargo-binstall = "latest"
chezmoi = "latest"
codex = "latest"
"conda:clang" = "latest"
crush = "latest"
delta = "latest"
dust = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
gemini = "latest"
gh = "latest"
"github:Genivia/ugrep" = "latest"
"github:pkgxdev/pkgx" = "latest"
"github:xmake-io/xmake" = "latest"
glow = "latest"
go = "latest"
hyperfine = "latest"
node = "latest"
"npm:@jetbrains/junie-cli" = "latest"
"npm:@kilocode/cli" = "latest"
"npm:@sourcegraph/amp" = "latest"
odin = "latest"
opencode = "latest"
"pipx:tldr" = "latest"
pnpm = "latest"
python = "latest"
ripgrep = "latest"
sd = "latest"
sqlite = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
yt-dlp = "latest"
zoxide = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[settings.cargo]
binstall = true

[settings.npm]
package_manager = "pnpm"

[settings.python]
compile = false
