[tools]
aqua = "latest"
"aqua:Wilfred/difftastic" = "latest"
"aqua:block/goose" = "latest"
"aqua:exercism/cli" = "latest"
"aqua:iawia002/lux" = "latest"
"aqua:microsoft/edit" = "1.2.1"
"aqua:nats-io/natscli" = "latest"
"aqua:nushell/nushell" = "latest"
"aqua:sst/opencode" = "latest"
"aqua:topgrade-rs/topgrade" = "latest"
"aqua:twistedpair/google-cloud-sdk" = "latest"
"aqua:zyedidia/micro" = "latest"
atuin = "latest"
bat = "latest"
bitwarden = "latest"
bottom = "latest"
bun = "latest"
carapace = "latest"
cargo-binstall = "latest"
chezmoi = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
cmake = "latest"
codex = "latest"
conan = "latest"
"conda:ruby" = "latest"
cosign = "latest"
delta = "latest"
dust = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
"github:AdguardTeam/AdGuardHome" = "latest"
"github:Canop/dysk" = "latest"
"github:Valkyrie00/bold-brew" = "latest"
"github:lucasgelfond/zerobrew" = "latest"
go = "latest"
"go:github.com/Gelio/go-global-update" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
hyperfine = "latest"
lsd = "latest"
node = "latest"
"npm:@github/copilot" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@kilocode/cli" = "latest"
ripgrep = "latest"
rust = "latest"
sd = "latest"
sqlite = "latest"
starship = "latest"
"github:danielmiessler/fabric" = "latest"
"github:xmake-io/xmake" = "latest"
usage = "latest"
uv = "latest"
yt-dlp = "latest"
zoxide = "latest"
pnpm = "latest"
"github:pkgforge/soar" = "latest"
"pipx:tldr" = "latest"
eza = "latest"
"github:uutils/coreutils" = "latest"
"github:uutils/diffutils" = "latest"
"github:uutils/findutils" = "latest"
"github:charmbracelet/crush" = "latest"
"github:abishekvashok/cmatrix" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[settings.npm]
package_manager = "pnpm"

[settings.python]
compile = false

[settings.ruby]
compile = false
